// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

package wirevalidator

import (
	"encoding/hex"
	"errors"
	"testing"

	npamp "github.com/bubblefish-tech/npamp_protocol/impl/go"
)

func testRegistries(t *testing.T) *Registries {
	t.Helper()
	reg, err := LoadDefault()
	if err != nil {
		t.Fatalf("LoadDefault: %v", err)
	}
	return reg
}

// ---------------------------------------------------------------------------
// F3 non-circular ACCEPT: the golden PING vector from the PINNED conformance
// corpus (test-vectors/v1/conformance-corpus.json, header.decode tcId 1),
// an independent authority this validator's own logic never produced.
// ---------------------------------------------------------------------------

// TestValidateBytes_AcceptsCorpusGoldenPING reproduces
// test-vectors/v1/conformance-corpus.json header.decode tcId=1 verbatim (the
// hex string is copied from that pinned, MANIFEST.sha256-covered file, not
// generated by this package) and proves ValidateBytes accepts it: Channel=0
// (Control, registered), Type=1 (PING, a universal system frame type),
// zero-length payload (well within MaxFrameSize).
func TestValidateBytes_AcceptsCorpusGoldenPING(t *testing.T) {
	reg := testRegistries(t)
	const goldenPINGHex = "4e50414d20000100000000000000000000000000000d880c250000000000000000000000"
	buf, err := hex.DecodeString(goldenPINGHex)
	if err != nil {
		t.Fatalf("decode corpus hex fixture: %v", err)
	}
	if err := ValidateBytes(reg, buf); err != nil {
		t.Fatalf("ValidateBytes rejected the corpus golden PING vector (header.decode tcId=1): %v", err)
	}
}

// TestValidateBytes_AcceptsControlHandshakeFrame proves a real
// channel-specific application-band frame type (CLIENT_HELLO, 0x0100, on
// its registered channel Control 0x0000) is accepted -- the frame-type-
// registered-for-channel positive path, not just the universal-system-type
// path the golden PING covers.
func TestValidateBytes_AcceptsControlHandshakeFrame(t *testing.T) {
	reg := testRegistries(t)
	wire, err := (&npamp.Frame{
		Type:    uint16(npamp.FrameClientHello),
		Channel: uint16(npamp.ChanControl),
		Seq:     0,
		Payload: []byte("cleartext client-hello payload placeholder"),
	}).MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}
	if err := ValidateBytes(reg, wire); err != nil {
		t.Fatalf("ValidateBytes rejected a CLIENT_HELLO frame on the Control channel: %v", err)
	}
}

// ---------------------------------------------------------------------------
// F3 non-circular REJECT: hand-constructed frames whose invalidity is
// established by reading registries/*.csv directly (an independent
// authority), never by consulting this validator's own logic.
// ---------------------------------------------------------------------------

// TestValidate_RejectsFrameTypeZero: registries/frame_types_reserved.csv row
// 1 reads "0x0000,(reserved),Reserved; MUST NOT be used as a frame type."
func TestValidate_RejectsFrameTypeZero(t *testing.T) {
	reg := testRegistries(t)
	err := reg.Validate(&npamp.Frame{Type: 0x0000, Channel: uint16(npamp.ChanControl)})
	assertReject(t, err, ReasonFrameTypeReserved)
}

// TestValidate_RejectsUnregisteredChannel: registries/channels.csv's last
// row is 0x0013 (Spatial); 0x00FF appears in none of its 20 rows.
func TestValidate_RejectsUnregisteredChannel(t *testing.T) {
	reg := testRegistries(t)
	err := reg.Validate(&npamp.Frame{Type: uint16(npamp.FramePing), Channel: 0x00FF})
	assertReject(t, err, ReasonChannelNotRegistered)
}

// TestValidate_RejectsFrameTypeNotRegisteredForChannel: reading
// registries/frame_types_channel.csv, Governance (channel_id 0x0004) has NO
// rows at all -- no companion or application-band frame type has been
// assigned to it -- while Governance itself IS a registered channel
// (channels.csv). A channel-specific frame type (CLIENT_HELLO's own numeric
// value 0x0100, which on Control means CLIENT_HELLO but carries no meaning
// on Governance) is therefore unregistered for this channel. This is the
// brief's named example: "an unregistered frame type" for the channel it
// arrives on.
func TestValidate_RejectsFrameTypeNotRegisteredForChannel(t *testing.T) {
	reg := testRegistries(t)
	err := reg.Validate(&npamp.Frame{Type: uint16(npamp.FrameClientHello), Channel: uint16(npamp.ChanGovernance)})
	assertReject(t, err, ReasonFrameTypeNotRegisteredForChannel)
}

// TestValidate_RejectsUnassignedGapFrameType: frame type 0x0050 falls in the
// companion-extension band (0x0030-0x00FF) but is not one of the specific
// ranges frame_types_reserved.csv reserves (0x0030-0x0036, 0x0060-0x0063,
// 0x0080, 0x0090, 0x00A0-0x00A3, 0x00B0-0x00B4, 0x00C0-0x00C4) and has no
// row in frame_types_channel.csv for any channel -- a plain unassigned gap.
func TestValidate_RejectsUnassignedGapFrameType(t *testing.T) {
	reg := testRegistries(t)
	err := reg.Validate(&npamp.Frame{Type: 0x0050, Channel: uint16(npamp.ChanControl)})
	assertReject(t, err, ReasonFrameTypeNotRegisteredForChannel)
}

// TestValidate_RejectsOverBoundsFrame: npamp.MaxFrameSize (frame.go) is the
// frozen 16 MiB cap; a payload one octet larger than the room left after the
// 36-octet header pushes the total one octet over.
func TestValidate_RejectsOverBoundsFrame(t *testing.T) {
	reg := testRegistries(t)
	payload := make([]byte, npamp.MaxFrameSize-npamp.HeaderSize+1)
	err := reg.Validate(&npamp.Frame{Type: uint16(npamp.FramePing), Channel: uint16(npamp.ChanControl), Payload: payload})
	assertReject(t, err, ReasonFrameTooLarge)
}

// TestValidate_AcceptsFrameAtExactMaxFrameSize proves the bound is
// inclusive (<=, not <): a frame at EXACTLY MaxFrameSize is accepted, only
// one octet more is rejected -- the off-by-one both directions of
// TestValidate_RejectsOverBoundsFrame depend on.
func TestValidate_AcceptsFrameAtExactMaxFrameSize(t *testing.T) {
	reg := testRegistries(t)
	payload := make([]byte, npamp.MaxFrameSize-npamp.HeaderSize)
	err := reg.Validate(&npamp.Frame{Type: uint16(npamp.FramePing), Channel: uint16(npamp.ChanControl), Payload: payload})
	if err != nil {
		t.Fatalf("Validate rejected a frame at exactly MaxFrameSize: %v", err)
	}
}

// TestValidateTLVSequence_RejectsUnregisteredTag: npamp-wire.cddl §6 states
// directly "tags 0x0E, 0x0F, 0x11 have no assignment (registry gaps)" --
// reading tlv_tags.csv confirms no row assigns 0x0E a name.
func TestValidateTLVSequence_RejectsUnregisteredTag(t *testing.T) {
	reg := testRegistries(t)
	err := reg.ValidateTLVSequence([]npamp.TLV{{Type: 0x0E, Value: []byte{0x01}}})
	assertReject(t, err, ReasonTLVTagNotRegistered)
}

// TestValidateTLVSequence_AcceptsRegisteredTag: tlv_tags.csv row 11 assigns
// 0x0A the name CertVerify.
func TestValidateTLVSequence_AcceptsRegisteredTag(t *testing.T) {
	reg := testRegistries(t)
	if err := reg.ValidateTLVSequence([]npamp.TLV{{Type: npamp.TLVCertVerify, Value: []byte{0x08, 0x07}}}); err != nil {
		t.Fatalf("ValidateTLVSequence rejected the registered CertVerify TLV: %v", err)
	}
}

// TestValidateTLVSequence_RejectsOverBoundsTLVCount: npamp.MaxTLVsPerFrame
// (tlv.go) is the frozen cap of 64; a hand-constructed slice of 65
// registered TLVs (bypassing npamp.DecodeTLVs, which would itself stop at
// the same bound) proves this validator's OWN defense-in-depth check works
// independent of DecodeTLVs.
func TestValidateTLVSequence_RejectsOverBoundsTLVCount(t *testing.T) {
	reg := testRegistries(t)
	tlvs := make([]npamp.TLV, npamp.MaxTLVsPerFrame+1)
	for i := range tlvs {
		tlvs[i] = npamp.TLV{Type: npamp.TLVProfileOffer, Value: []byte{0x01}}
	}
	err := reg.ValidateTLVSequence(tlvs)
	assertReject(t, err, ReasonTooManyTLVs)
}

// TestValidateErrorCode_RejectsUnassignedCode: registries/error_codes.csv's
// last row reads "0x000B-0x00FF,(reserved),-,Unassigned; reserved to this
// specification for future core conditions" -- 200 (0xC8) falls in that
// unassigned range and is not one of the ten rows 1-10.
func TestValidateErrorCode_RejectsUnassignedCode(t *testing.T) {
	reg := testRegistries(t)
	err := reg.ValidateErrorCode(npamp.SessionErrorCode(200))
	assertReject(t, err, ReasonErrorCodeNotRegistered)
}

// TestValidateErrorCode_RejectsReservedZero: error_codes.csv row 1 reads
// "0,(reserved),-,Reserved; MUST NOT be sent."
func TestValidateErrorCode_RejectsReservedZero(t *testing.T) {
	reg := testRegistries(t)
	err := reg.ValidateErrorCode(npamp.SessionErrorCode(0))
	assertReject(t, err, ReasonErrorCodeNotRegistered)
}

// TestValidateErrorCode_AcceptsRegisteredCode: error_codes.csv row 4 assigns
// code 3 the name replay_detected.
func TestValidateErrorCode_AcceptsRegisteredCode(t *testing.T) {
	reg := testRegistries(t)
	if err := reg.ValidateErrorCode(npamp.ErrCodeReplayDetected); err != nil {
		t.Fatalf("ValidateErrorCode rejected the registered code replay_detected (3): %v", err)
	}
}

// assertReject fails the test unless err is a *RejectError with the given
// Reason -- proving both that the call actually rejected (not merely
// returned some unrelated error) and that it named the RIGHT reason (a
// stub that always returns the same RejectReason would fail this on every
// case but one, which is exactly the point).
func assertReject(t *testing.T, err error, want RejectReason) {
	t.Helper()
	if err == nil {
		t.Fatalf("got nil error, want a *RejectError with reason %q", want)
	}
	var re *RejectError
	if !errors.As(err, &re) {
		t.Fatalf("got error %v (%T), want a *RejectError with reason %q", err, err, want)
	}
	if re.Reason != want {
		t.Fatalf("got RejectError reason %q, want %q (detail: %s)", re.Reason, want, re.Detail)
	}
}
