// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

package codecbind_test

// codecbind_test.go grades the codecbind binding two ways (F3, non-circular):
//
//  1. Byte-identity round-trip: real "capability.body.decode" object vectors are taken from
//     the PINNED conformance corpus (test-vectors/v1/conformance-corpus.json, listed in
//     GitHub/MANIFEST.sha256), whose bytes and structure come from an independent,
//     from-scratch Python oracle (test-vectors/gen/capability_oracle.py) — never from this Go
//     implementation. Each vector's body is decoded via codecbind.Decode and re-encoded via
//     codecbind.Encode; the result MUST be byte-identical to the corpus bytes.
//  2. Constructed-object encode: for the same three vectors, the semantic object each body
//     represents (per the oracle's own field layout — see capability_oracle.go issue_body /
//     delegate_body / revoke_body and 84_capability_channel.md sections 6.1/6.2/6.4) is built
//     as a fresh Go map literal, independent of any decode step, and encoded via
//     codecbind.Encode; the result MUST match the corpus byte-vector.
//
// Fail-closed tests separately confirm Decode rejects a duplicate-key map, a float in a
// forbidden position, and a non-canonical (non-shortest-form) encoding, each via one of
// codecbind's re-exported named errors (errors.Is), unchanged from the Part-1 codec's own
// rejection.

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/bubblefish-tech/npamp_protocol/impl/go/codecbind"
)

// corpusDir is the pinned, language-agnostic test-vector corpus, relative to
// impl/go/codecbind — the same directory depth and relative path
// impl/go/hybridkem/hybridkem_kat_test.go uses for its own KAT files. The files under it are
// frozen (GitHub/MANIFEST.sha256) and MUST NOT be regenerated by an implementation under test.
var corpusDir = filepath.Join("..", "..", "..", "test-vectors", "v1")

type corpusFile struct {
	TestGroups []struct {
		Op      string `json:"op"`
		Profile string `json:"profile"`
		Tests   []struct {
			TcID    int    `json:"tcId"`
			Comment string `json:"comment"`
			In      struct {
				FrameType int    `json:"frameType"`
				Body      string `json:"body"`
			} `json:"in"`
			Result string `json:"result"`
		} `json:"tests"`
	} `json:"testGroups"`
}

// loadCapabilityBodyVectors returns the "capability.body.decode" / Standard test group's
// tcId 1, 2, and 3 — three real, independently-oracled canonical-CBOR object vectors — from
// the pinned corpus.
func loadCapabilityBodyVectors(t *testing.T) []struct {
	TcID    int
	Comment string
	Body    []byte
} {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(corpusDir, "conformance-corpus.json"))
	if err != nil {
		t.Fatalf("read pinned corpus: %v", err)
	}
	var cf corpusFile
	if err := json.Unmarshal(raw, &cf); err != nil {
		t.Fatalf("parse pinned corpus: %v", err)
	}
	var group *struct {
		Op      string `json:"op"`
		Profile string `json:"profile"`
		Tests   []struct {
			TcID    int    `json:"tcId"`
			Comment string `json:"comment"`
			In      struct {
				FrameType int    `json:"frameType"`
				Body      string `json:"body"`
			} `json:"in"`
			Result string `json:"result"`
		} `json:"tests"`
	}
	for i := range cf.TestGroups {
		if cf.TestGroups[i].Op == "capability.body.decode" && cf.TestGroups[i].Profile == "Standard" {
			group = &cf.TestGroups[i]
			break
		}
	}
	if group == nil {
		t.Fatalf("pinned corpus: no capability.body.decode/Standard test group found")
	}
	want := map[int]bool{1: true, 2: true, 3: true}
	var out []struct {
		TcID    int
		Comment string
		Body    []byte
	}
	for _, tc := range group.Tests {
		if !want[tc.TcID] || tc.Result != "valid" {
			continue
		}
		b, err := hex.DecodeString(tc.In.Body)
		if err != nil {
			t.Fatalf("corpus tcId %d: bad hex body %q: %v", tc.TcID, tc.In.Body, err)
		}
		out = append(out, struct {
			TcID    int
			Comment string
			Body    []byte
		}{tc.TcID, tc.Comment, b})
	}
	if len(out) != 3 {
		t.Fatalf("pinned corpus: expected exactly tcId 1,2,3 (valid) in capability.body.decode/Standard, got %d entries", len(out))
	}
	return out
}

// TestByteIdentityRoundTrip decodes each of 3 real pinned-corpus object vectors via
// codecbind.Decode and re-encodes the decoded value via codecbind.Encode, asserting the result
// is byte-identical to the corpus's own bytes (never to a value this test or this
// implementation produced independently).
func TestByteIdentityRoundTrip(t *testing.T) {
	vectors := loadCapabilityBodyVectors(t)
	for _, v := range vectors {
		v := v
		t.Run(v.Comment, func(t *testing.T) {
			decoded, err := codecbind.Decode(v.Body)
			if err != nil {
				t.Fatalf("tcId %d: Decode: %v", v.TcID, err)
			}
			reEncoded, err := codecbind.Encode(decoded)
			if err != nil {
				t.Fatalf("tcId %d: Encode(decoded): %v", v.TcID, err)
			}
			if !bytes.Equal(reEncoded, v.Body) {
				t.Fatalf("tcId %d: round-trip mismatch:\n corpus   = %x\n re-encoded = %x", v.TcID, v.Body, reEncoded)
			}
		})
	}
}

// TestEncodeConstructedObjectMatchesCorpus builds, as fresh Go map literals with no decode
// step involved, the exact semantic object each of the 3 pinned-corpus vectors represents
// (cross-checked by hand against test-vectors/gen/capability_oracle.py's issue_body /
// delegate_body / revoke_body field layout and 84_capability_channel.md sections
// 6.1/6.2/6.4), encodes each via codecbind.Encode, and asserts the result matches the corpus
// byte-vector exactly.
func TestEncodeConstructedObjectMatchesCorpus(t *testing.T) {
	vectors := loadCapabilityBodyVectors(t)
	byTcID := make(map[int][]byte, len(vectors))
	for _, v := range vectors {
		byTcID[v.TcID] = v.Body
	}

	cases := []struct {
		name  string
		tcID  int
		value map[uint64]any
	}{
		{
			// capability_oracle.py issue_body(): envelope(frame_kind=CAP_ISSUE_REQ=0x0100,
			// corr=0x7a) + subject(2)="agent-b" + authority(3)="read:ledger" +
			// effect(9)=non_idempotent_write(0x02). 84_capability_channel.md section 6.1.
			name: "CAP_ISSUE_REQ",
			tcID: 1,
			value: map[uint64]any{
				0: uint64(0x0100),
				1: []byte{0x7a},
				2: "agent-b",
				3: "read:ledger",
				9: uint64(0x02),
			},
		},
		{
			// capability_oracle.py delegate_body(): envelope(frame_kind=CAP_DELEGATE_REQ=0x0102,
			// corr=0x7a) + token_id(2)="cap-1" + subject(3)="agent-c" +
			// effect(7)=non_idempotent_write(0x02). 84_capability_channel.md section 6.2.
			name: "CAP_DELEGATE_REQ",
			tcID: 2,
			value: map[uint64]any{
				0: uint64(0x0102),
				1: []byte{0x7a},
				2: "cap-1",
				3: "agent-c",
				7: uint64(0x02),
			},
		},
		{
			// capability_oracle.py revoke_body(): envelope(frame_kind=CAP_REVOKE_REQ=0x0104,
			// corr=0x7a) + token_id(2)="cap-1" + effect(5)=destructive(0x03).
			// 84_capability_channel.md section 6.4.
			name: "CAP_REVOKE_REQ",
			tcID: 3,
			value: map[uint64]any{
				0: uint64(0x0104),
				1: []byte{0x7a},
				2: "cap-1",
				5: uint64(0x03),
			},
		},
	}

	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			want, ok := byTcID[c.tcID]
			if !ok {
				t.Fatalf("no pinned-corpus vector loaded for tcId %d", c.tcID)
			}
			got, err := codecbind.Encode(c.value)
			if err != nil {
				t.Fatalf("Encode(%s): %v", c.name, err)
			}
			if !bytes.Equal(got, want) {
				t.Fatalf("%s: constructed encoding does not match corpus vector:\n corpus      = %x\n constructed = %x", c.name, want, got)
			}
		})
	}
}

// TestDecodeRejectsDuplicateKey feeds Decode a well-formed-looking canonical CBOR map whose
// two entries share the same key (0x00 twice) — bytes: a2 00 00 00 01 (map(2){0:0, 0:1}). The
// second key is not strictly greater than the first, so this MUST be rejected as a map-order
// violation, unchanged from the Part-1 codec (memory_cbor.go's cborDecode, map case).
func TestDecodeRejectsDuplicateKey(t *testing.T) {
	b := []byte{0xa2, 0x00, 0x00, 0x00, 0x01}
	v, err := codecbind.Decode(b)
	if err == nil {
		t.Fatalf("Decode(duplicate-key map) = %#v, nil; want ErrMapKeyOrder", v)
	}
	if !errors.Is(err, codecbind.ErrMapKeyOrder) {
		t.Fatalf("Decode(duplicate-key map) error = %v; want errors.Is(..., ErrMapKeyOrder)", err)
	}
}

// TestDecodeRejectsFloatInForbiddenPosition feeds Decode a canonical-looking map whose one
// value is an IEEE-754 single-precision float (major 7, additional info 26) — bytes:
// a1 00 fa 00 00 00 00 (map(1){0: float32(0.0)}). This deterministic profile accepts no float
// anywhere (memory_cbor.go's doc comment: "REJECTS ... floats"), so every position is a
// forbidden position; this MUST be rejected as an unsupported item, unchanged from Part-1.
func TestDecodeRejectsFloatInForbiddenPosition(t *testing.T) {
	b := []byte{0xa1, 0x00, 0xfa, 0x00, 0x00, 0x00, 0x00}
	v, err := codecbind.Decode(b)
	if err == nil {
		t.Fatalf("Decode(map with float value) = %#v, nil; want ErrUnsupportedItem", v)
	}
	if !errors.Is(err, codecbind.ErrUnsupportedItem) {
		t.Fatalf("Decode(map with float value) error = %v; want errors.Is(..., ErrUnsupportedItem)", err)
	}
}

// TestDecodeRejectsNonCanonicalEncoding feeds Decode a top-level unsigned integer 0 encoded in
// the two-byte (ai=24) form (0x18 0x00) rather than its one-byte shortest form (0x00) — a
// non-canonical encoding under RFC 8949 section 4.2.1. This MUST be rejected as not-shortest,
// unchanged from the Part-1 codec (memory_cbor.go's decodeArg, ai==24 case).
func TestDecodeRejectsNonCanonicalEncoding(t *testing.T) {
	b := []byte{0x18, 0x00}
	v, err := codecbind.Decode(b)
	if err == nil {
		t.Fatalf("Decode(non-canonical uint 0) = %#v, nil; want ErrNotShortestForm", v)
	}
	if !errors.Is(err, codecbind.ErrNotShortestForm) {
		t.Fatalf("Decode(non-canonical uint 0) error = %v; want errors.Is(..., ErrNotShortestForm)", err)
	}
}

// TestEncodeUnsupportedGoTypeIsAnErrorNotAPanic confirms Encode's panic-recovery boundary
// (codecbind.go) actually engages: encoding a Go type outside the accepted set (a bare
// float64, which the Part-1 codec's cborEncode has no case for) must return
// ErrUnsupportedGoType rather than panicking out of Encode.
func TestEncodeUnsupportedGoTypeIsAnErrorNotAPanic(t *testing.T) {
	_, err := codecbind.Encode(3.14)
	if err == nil {
		t.Fatalf("Encode(float64) = nil error; want ErrUnsupportedGoType")
	}
	if !errors.Is(err, codecbind.ErrUnsupportedGoType) {
		t.Fatalf("Encode(float64) error = %v; want errors.Is(..., ErrUnsupportedGoType)", err)
	}
}

// TestMustEncodePanicsOnUnsupportedGoType confirms MustEncode preserves the Part-1 codec's
// unrecovered panic behavior exactly (no softening at that boundary).
func TestMustEncodePanicsOnUnsupportedGoType(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatalf("MustEncode(float64) did not panic; want a panic (Part-1 cborEncode behavior)")
		}
	}()
	_ = codecbind.MustEncode(3.14)
}
