package npamp

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// katDir is the pinned, language-agnostic test-vector corpus, relative to
// impl/go. The files under it are frozen (MANIFEST.sha256) and MUST NOT be
// regenerated by an implementation under test.
var katDir = filepath.Join("..", "..", "test-vectors", "v1")

// loadKAT reads and parses one KAT file from the pinned corpus into v.
func loadKAT(t *testing.T, name string, v any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(katDir, name))
	if err != nil {
		t.Fatalf("read KAT %s: %v", name, err)
	}
	if err := json.Unmarshal(raw, v); err != nil {
		t.Fatalf("parse KAT %s: %v", name, err)
	}
}

// mustHex decodes a hex field or fails the test.
func mustHex(t *testing.T, field, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex field %s: %v", field, err)
	}
	return b
}

// mustHexU16 parses a "0xNNNN" hex code point or fails the test.
func mustHexU16(t *testing.T, field, s string) uint16 {
	t.Helper()
	n, err := strconv.ParseUint(strings.TrimPrefix(s, "0x"), 16, 16)
	if err != nil {
		t.Fatalf("hex code point %s = %q: %v", field, s, err)
	}
	return uint16(n)
}

// concat returns a || b in a fresh slice (no aliasing of either input).
func concat(a, b []byte) []byte {
	out := make([]byte, 0, len(a)+len(b))
	out = append(out, a...)
	return append(out, b...)
}
