// Copyright (c) 2026 BubbleFish Technologies, Inc. Apache-2.0.

package hybridkem_test

// hybridkem_kat_test.go grades the standalone adapter (F3, non-circular):
// each combiner's output is checked against standards-anchored expected
// values (NIST ACVP FIPS 203, RFC 7748 section 6.1, RFC 5903 section 8.2 —
// the same anchors kemwire_kat_test.go and kem1024_kat_test.go use, reused
// here rather than re-derived), and separately cross-checked byte-identical
// against the root package's SharedSecrets.Combined() / SharedSecrets1024.
// Combined() for the SAME real key-exchange inputs, so the extraction cannot
// silently diverge from the reference it was extracted from.

import (
	"bytes"
	"crypto/ecdh"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	npamp "github.com/bubblefish-tech/npamp_protocol/impl/go"
	"github.com/bubblefish-tech/npamp_protocol/impl/go/hybridkem"
)

// katDir is the pinned, language-agnostic test-vector corpus, relative to
// impl/go/hybridkem. The files under it are frozen (MANIFEST.sha256) and
// MUST NOT be regenerated by an implementation under test.
var katDir = filepath.Join("..", "..", "..", "test-vectors", "v1")

func loadKAT(t *testing.T, name string, v any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(katDir, name))
	if err != nil {
		t.Fatalf("read KAT %s: %v", name, err)
	}
	if err := json.Unmarshal(raw, v); err != nil {
		t.Fatalf("parse KAT %s: %v", name, err)
	}
}

func mustHex(t *testing.T, field, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex field %s: %v", field, err)
	}
	return b
}

func mustHexU16(t *testing.T, field, s string) uint16 {
	t.Helper()
	n, err := strconv.ParseUint(strings.TrimPrefix(s, "0x"), 16, 16)
	if err != nil {
		t.Fatalf("hex code point %s = %q: %v", field, s, err)
	}
	return uint16(n)
}

func concat(a, b []byte) []byte {
	out := make([]byte, 0, len(a)+len(b))
	out = append(out, a...)
	return append(out, b...)
}

// kemWireKAT mirrors test-vectors/v1/kem-wire-kat.json (the same struct shape
// as ../kemwire_kat_test.go's kemWireKAT), standards-derived (NIST ACVP FIPS
// 203; RFC 7748 section 6.1), non-circular.
type kemWireKAT struct {
	KEMCodepoint string `json:"kem_codepoint"`
	Keygen       struct {
		D  string `json:"d"`
		Z  string `json:"z"`
		EK string `json:"ek"`
	} `json:"mlkem768_keygen"`
	X25519 struct {
		AlicePrivate string `json:"alice_private"`
		AlicePublic  string `json:"alice_public"`
		BobPrivate   string `json:"bob_private"`
		BobPublic    string `json:"bob_public"`
		SharedSecret string `json:"shared_secret"`
	} `json:"x25519_rfc7748_6_1"`
	DecapsRef struct {
		SharedSecretK string `json:"shared_secret_K"`
	} `json:"mlkem768_decaps_reference"`
	WireLayout struct {
		KEMShareLen       int `json:"kem_share_len"`
		KEMCiphertextLen  int `json:"kem_ciphertext_len"`
		CombinedSecretLen int `json:"combined_secret_len"`
	} `json:"wire_layout"`
}

// TestCombineX25519MLKEM768_RFCAnchored pins the ML-KEM-first order directly
// against the standards-anchored values kem-wire-kat.json carries: the NIST
// ACVP FIPS 203 ML-KEM-768 decapsulation-reference shared secret and the RFC
// 7748 section 6.1 X25519 shared secret. Neither value is generated by this
// package or by the npamp reference implementation.
func TestCombineX25519MLKEM768_RFCAnchored(t *testing.T) {
	var kat kemWireKAT
	loadKAT(t, "kem-wire-kat.json", &kat)

	if got := mustHexU16(t, "kem_codepoint", kat.KEMCodepoint); hybridkem.Group(got) != hybridkem.X25519MLKEM768 {
		t.Fatalf("kem_codepoint = 0x%04x, want 0x%04x", got, uint16(hybridkem.X25519MLKEM768))
	}

	kNIST := mustHex(t, "shared_secret_K", kat.DecapsRef.SharedSecretK) // NIST ACVP FIPS 203 anchor
	xss := mustHex(t, "shared_secret", kat.X25519.SharedSecret)        // RFC 7748 section 6.1 anchor

	got, err := hybridkem.Combine(hybridkem.X25519MLKEM768, kNIST, xss)
	if err != nil {
		t.Fatalf("Combine(X25519MLKEM768): %v", err)
	}
	if len(got) != kat.WireLayout.CombinedSecretLen || len(got) != hybridkem.CombinedSecretSizeX25519MLKEM768 {
		t.Fatalf("combined secret len = %d, want %d", len(got), kat.WireLayout.CombinedSecretLen)
	}
	if !bytes.Equal(got, concat(kNIST, xss)) {
		t.Fatal("Combine(X25519MLKEM768) is not ML-KEM_ss || X25519_ss")
	}
	if bytes.Equal(got, concat(xss, kNIST)) {
		t.Fatal("Combine(X25519MLKEM768) unexpectedly also matches the reversed (X25519-first) order")
	}
}

// TestCombineX25519MLKEM768_CrossCheck drives the REAL X25519MLKEM768
// exchange through the root npamp package (whose values are themselves
// anchored to RFC 7748 section 6.1 and NIST ACVP by ../kemwire_kat_test.go)
// and asserts hybridkem.Combine on the raw component secrets is byte-
// identical to SharedSecrets.Combined() for the same inputs.
func TestCombineX25519MLKEM768_CrossCheck(t *testing.T) {
	var kat kemWireKAT
	loadKAT(t, "kem-wire-kat.json", &kat)

	seed := concat(mustHex(t, "d", kat.Keygen.D), mustHex(t, "z", kat.Keygen.Z))
	alicePriv := mustHex(t, "alice_private", kat.X25519.AlicePrivate)
	bobPriv := mustHex(t, "bob_private", kat.X25519.BobPrivate)

	client, err := npamp.NewKEMClient(seed, alicePriv)
	if err != nil {
		t.Fatal(err)
	}
	bob, err := ecdh.X25519().NewPrivateKey(bobPriv)
	if err != nil {
		t.Fatal(err)
	}
	share := client.KEMShare()
	ct, serverSS, err := npamp.EncapsulateWith(share, bob)
	if err != nil {
		t.Fatal(err)
	}
	clientSS, err := client.SharedSecrets(ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(clientSS.MLKEM, serverSS.MLKEM) || !bytes.Equal(clientSS.X25519, serverSS.X25519) {
		t.Fatal("client/server component shared secrets disagree (exchange broken, not an adapter issue)")
	}

	adapterOut, err := hybridkem.Combine(hybridkem.X25519MLKEM768, clientSS.MLKEM, clientSS.X25519)
	if err != nil {
		t.Fatalf("Combine(X25519MLKEM768): %v", err)
	}
	refOut := clientSS.Combined()
	if !bytes.Equal(adapterOut, refOut) {
		t.Fatalf("hybridkem.Combine diverges from npamp.SharedSecrets.Combined(): got %x, want %x", adapterOut, refOut)
	}
}

// RFC 5903 section 8.2 (384-Bit Random ECP Group / Group 20) is the published,
// standards-anchored secp384r1 ECDH known-answer vector — the same literal
// values ../kem1024_kat_test.go anchors its ordering leg to, reused here
// directly from the RFC rather than re-derived from that test file.
const (
	rfc5903P384InitiatorPriv = "099F3C7034D4A2C699884D73A375A67F7624EF7C6B3C0F160647B67414DCE655E35B538041E649EE3FAEF896783AB194"
	rfc5903P384ResponderPriv = "41CB0779B4BDB85D47846725FBEC3C9430FAB46CC8DC5060855CC9BDA0AA2942E0308312916B8ED2960E4BD55A7448FC"
	rfc5903P384ResponderX    = "E558DBEF53EECDE3D3FCCFC1AEA08A89A987475D12FD950D83CFA41732BC509D0D1AC43A0336DEF96FDA41D0774A3571"
	rfc5903P384ResponderY    = "DCFBEC7AACF3196472169E838430367F66EEBE3C6E70C416DD5F0C68759DD1FFF83FA40142209DFF5EAAD96DB9E6386C"
	rfc5903P384SharedX       = "11187331C279962D93D604243FD592CB9D0A926F422E47187521287E7156C5C4D603135569B9E9D09CF5D4A270F59746"
)

// TestCombineSecP384r1MLKEM1024_RFCAnchored pins the classical(P-384)-first
// order directly against the RFC 5903 section 8.2 secp384r1 ECDH shared
// secret (girx), independently recomputed here via crypto/ecdh from the raw
// RFC private scalars — not taken from the npamp reference implementation.
func TestCombineSecP384r1MLKEM1024_RFCAnchored(t *testing.T) {
	iPriv := mustHex(t, "i", rfc5903P384InitiatorPriv)
	rPriv := mustHex(t, "r", rfc5903P384ResponderPriv)
	rPubWant := concat(concat([]byte{0x04}, mustHex(t, "grx", rfc5903P384ResponderX)), mustHex(t, "gry", rfc5903P384ResponderY))
	girxWant := mustHex(t, "girx", rfc5903P384SharedX)

	iKey, err := ecdh.P384().NewPrivateKey(iPriv)
	if err != nil {
		t.Fatal(err)
	}
	rKey, err := ecdh.P384().NewPrivateKey(rPriv)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(rKey.PublicKey().Bytes(), rPubWant) {
		t.Fatal("responder public key does not reproduce RFC 5903 section 8.2 (0x04||grx||gry)")
	}
	rPub, err := ecdh.P384().NewPublicKey(rPubWant)
	if err != nil {
		t.Fatal(err)
	}
	ecdhSS, err := iKey.ECDH(rPub)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ecdhSS, girxWant) {
		t.Fatal("secp384r1 ECDH shared secret does not reproduce RFC 5903 section 8.2 girx")
	}

	// A fixed, arbitrary-but-deterministic ML-KEM-1024 component secret: the
	// combiner-order assertion below checks only the POSITION of the ML-KEM
	// component in the concatenation, not its value, so an arbitrary byte
	// pattern suffices here. A NIST-ACVP-anchored ML-KEM-1024 (d,z,ek) value
	// (closing the gap this comment used to name as tracked-not-anchored,
	// T18.3) now exists at ../kem1024_acvp_test.go, which checks the value
	// crypto/mlkem.NewDecapsulationKey1024 actually produces from a seed —
	// a different, complementary property from the order check below.
	mlkemSS := make([]byte, hybridkem.MLKEMSharedSecretSize)
	for i := range mlkemSS {
		mlkemSS[i] = byte(0xa0 + i)
	}

	got, err := hybridkem.Combine(hybridkem.SecP384r1MLKEM1024, mlkemSS, ecdhSS)
	if err != nil {
		t.Fatalf("Combine(SecP384r1MLKEM1024): %v", err)
	}
	if len(got) != hybridkem.CombinedSecretSizeSecP384r1MLKEM1024 {
		t.Fatalf("combined secret len = %d, want %d", len(got), hybridkem.CombinedSecretSizeSecP384r1MLKEM1024)
	}
	if !bytes.Equal(got, concat(girxWant, mlkemSS)) {
		t.Fatal("Combine(SecP384r1MLKEM1024) is not ECDHE_ss || ML-KEM_ss (must be classical/P-384-first)")
	}
	if bytes.Equal(got, concat(mlkemSS, girxWant)) {
		t.Fatal("Combine(SecP384r1MLKEM1024) unexpectedly also matches the ML-KEM-first (X25519MLKEM768) order")
	}
}

// TestCombineSecP384r1MLKEM1024_CrossCheck drives the REAL SecP384r1MLKEM1024
// exchange through the root npamp package, using the RFC 5903 section 8.2
// keys on both sides (so the ECDHE half is standards-anchored), and asserts
// hybridkem.Combine on the raw component secrets is byte-identical to
// SharedSecrets1024.Combined() for the same inputs.
func TestCombineSecP384r1MLKEM1024_CrossCheck(t *testing.T) {
	iPriv := mustHex(t, "i", rfc5903P384InitiatorPriv)
	rPriv := mustHex(t, "r", rfc5903P384ResponderPriv)
	girxWant := mustHex(t, "girx", rfc5903P384SharedX)

	rKey, err := ecdh.P384().NewPrivateKey(rPriv)
	if err != nil {
		t.Fatal(err)
	}

	seed := make([]byte, 64)
	for j := range seed {
		seed[j] = byte(j)
	}
	client, err := npamp.NewKEMClient1024(seed, iPriv)
	if err != nil {
		t.Fatal(err)
	}
	share := client.KEMShare()
	ct, serverSS, err := npamp.EncapsulateWith1024(share, rKey)
	if err != nil {
		t.Fatal(err)
	}
	clientSS, err := client.SharedSecrets(ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(clientSS.ECDHE, girxWant) {
		t.Fatal("client-decapsulated ECDHE shared secret does not reproduce RFC 5903 section 8.2 girx")
	}
	if !bytes.Equal(clientSS.MLKEM, serverSS.MLKEM) || !bytes.Equal(clientSS.ECDHE, serverSS.ECDHE) {
		t.Fatal("client/server component shared secrets disagree (exchange broken, not an adapter issue)")
	}

	adapterOut, err := hybridkem.Combine(hybridkem.SecP384r1MLKEM1024, clientSS.MLKEM, clientSS.ECDHE)
	if err != nil {
		t.Fatalf("Combine(SecP384r1MLKEM1024): %v", err)
	}
	refOut := clientSS.Combined()
	if !bytes.Equal(adapterOut, refOut) {
		t.Fatalf("hybridkem.Combine diverges from npamp.SharedSecrets1024.Combined(): got %x, want %x", adapterOut, refOut)
	}
}

// TestCombineErrors exercises the adapter's input-validation surface: an
// unknown group and wrong-length component secrets must be rejected, never
// silently truncated or padded.
func TestCombineErrors(t *testing.T) {
	mlkemSS := make([]byte, hybridkem.MLKEMSharedSecretSize)
	x25519SS := make([]byte, hybridkem.X25519SharedSecretSize)
	p384SS := make([]byte, hybridkem.P384SharedSecretSize)

	if _, err := hybridkem.Combine(hybridkem.Group(0xffff), mlkemSS, x25519SS); err != hybridkem.ErrUnknownGroup {
		t.Fatalf("unknown group: err = %v, want %v", err, hybridkem.ErrUnknownGroup)
	}
	if _, err := hybridkem.Combine(hybridkem.X25519MLKEM768, mlkemSS[:31], x25519SS); err != hybridkem.ErrMLKEMSecretSize {
		t.Fatalf("short ML-KEM secret: err = %v, want %v", err, hybridkem.ErrMLKEMSecretSize)
	}
	if _, err := hybridkem.Combine(hybridkem.X25519MLKEM768, mlkemSS, x25519SS[:31]); err != hybridkem.ErrClassicalSecretSize {
		t.Fatalf("short X25519 secret: err = %v, want %v", err, hybridkem.ErrClassicalSecretSize)
	}
	if _, err := hybridkem.Combine(hybridkem.SecP384r1MLKEM1024, mlkemSS, x25519SS); err != hybridkem.ErrClassicalSecretSize {
		t.Fatalf("X25519-sized secret passed to SecP384r1MLKEM1024: err = %v, want %v", err, hybridkem.ErrClassicalSecretSize)
	}
	if _, err := hybridkem.Combine(hybridkem.SecP384r1MLKEM1024, mlkemSS, p384SS); err != nil {
		t.Fatalf("valid SecP384r1MLKEM1024 inputs: unexpected err = %v", err)
	}
}
